# Generated by Django 4.2 on 2023-05-09 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TabulatorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('command', models.CharField(max_length=20)),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.tabulator')),
            ],
            options={
                'unique_together': {('form_id', 'tab')},
            },
        ),
        migrations.CreateModel(
            name='DependantTabulatorOption',
            fields=[
                ('tabulatoroption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compiler.tabulatoroption')),
                ('dependant_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_options', to='compiler.tabulatoroption')),
            ],
            bases=('compiler.tabulatoroption',),
        ),
    ]
