# Generated by Django 4.2 on 2023-05-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_alter_tabulatoroption_tab_delete_tabulator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabulatoroption',
            name='tab',
            field=models.CharField(choices=[('STANDARD', 'STANDARD')], max_length=20),
        ),
    ]
