# Generated by Django 4.2 on 2023-05-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0006_alter_tabulatoroption_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesection',
            name='status',
            field=models.CharField(choices=[('COMPILATION_SUCCESSFUL', 'COMPILATION_SUCCESSFUL'), ('COMPILATION_WARNINGS', 'COMPILATION_WARNINGS'), ('COMPILATION_ERRORS', 'COMPILATION_ERRORS')], default='COMPILATION_SUCCESSFUL', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filesection',
            name='type',
            field=models.CharField(choices=[('PROCEDURE', 'PROCEDURE'), ('COMMENT', 'COMMENT'), ('COMPILER_DIRECTIVES', 'COMPILER_DIRECTIVES'), ('VARIABLE_DECLARATION', 'VARIABLE_DECLARATION'), ('INLINE_ASSEMBLY', 'INLINE_ASSEMBLY')], default='PROCEDURE', max_length=20),
            preserve_default=False,
        ),
    ]
